### ISSUE TITLE
关于弹幕顶部底部显示不能居中的问题

### ISSUE THREAD

**Issue by z5qdi59** [wangzmgit/vue-wplayer#1]
您好，您这个播放器非常好用，但当我使用type=1、2的时候，弹幕只会卡在播放界面的右边沿没法居中
{
        "time": 1,
        "type": 1,
        "color": "#aaaaaa",
        "text": "我自愿的"
    },
请问这是什么原因呢？

**Comment by z5qdi59** [comment]
使用的是mp4格式，电脑端播放

**Comment by z5qdi59** [comment]
![f3effb3cdc0474a70bf6d414cc30915](https://user-images.githubusercontent.com/51902030/207093777-56420866-095b-4232-ad9c-48bf4984df69.png)
这会运行位置变了些，但是还是不是居中的

**Comment by z5qdi59** [comment]
![f3effb3cdc0474a70bf6d414cc30915](https://user-images.githubusercontent.com/51902030/207094117-99b7d832-60e0-4132-9455-747ebdd2b04f.png)

这会有所变化，但还不是居中

**Comment by wangzmgit** [comment]
刚才测试了一下，没有出现这个问题，麻烦提供一下在播放器上添加的样式，和浏览器种类及版本

**Comment by z5qdi59** [comment]
Google Chrome 版本 107.0.5304.63（正式版本） （64 位）

**Comment by wangzmgit** [comment]
在App.vue文件中，把style下的#app中的`text-align: center;`注释掉就可以了。

**Comment by z5qdi59** [comment]
666，解决了
这是全局设置居中，然后弹幕又自己设置居中，因此正好变成一个屏幕宽而不是半个屏幕宽？就没能居中？

**Comment by wangzmgit** [comment]
固定弹幕的宽度为播放器的宽度，全局设置居中后，固定弹幕最左侧在播放器中间位置，所以弹幕会出现在右侧，并且只显示一半。
