### ISSUE TITLE
动态添加弹幕到数组中,视频组件不会播放新添加的弹幕么？

### ISSUE THREAD

**Issue by Rookie-JiaChen** [wangzmgit/vue-wplayer#2]
我开了两个视频播放窗口都连接上了websocket，在其中一个窗口发送弹幕时，将弹幕信息传送到后端，再通过后端发送websocket消息到前端，并将弹幕信息添加到数组中。

但是另一个窗口并不会播放这个新弹幕.
```
 const onMessage = (event) => {
                console.log('WebSocket收到消息：', event.data);
                //将后端发来的消息转为对象
                let oldDanmuInfo=JSON.parse(event.data);
                //判断videoId是否相同
                if(route.query.id==oldDanmuInfo.videoId){

                    let newDanmuInfo={
                        time: oldDanmuInfo.danmuTime,
                        color: oldDanmuInfo.color,
                        type: oldDanmuInfo.type,
                        text: oldDanmuInfo.content
                    }
                    //将后端推送的信息放入弹幕数组中
                    options.value.danmaku.data.push(newDanmuInfo);
                    console.log('添加到弹幕数组',options.value.danmaku.data);
                }
                // ElMessage.success("收到消息: ",event.data);
            };
```

![Snipaste_2023-02-09_17-28-06](https://user-images.githubusercontent.com/17950010/217772361-fee97f64-81cd-4179-9d67-c3ad727f2b77.png)

**Comment by wangzmgit** [comment]
因为这个弹幕功能不是实时的，在初始化的时候会根据过滤要求添加到一个新的弹幕数组中，所以修改弹幕数组没有效果。我现在正在重构这个项目，会尽可能的解决这个问题。

**Comment by Rookie-JiaChen** [comment]
> 因为这个弹幕功能不是实时的，在初始化的时候会根据过滤要求添加到一个新的弹幕数组中，所以修改弹幕数组没有效果。我现在正在重构这个项目，会尽可能的解决这个问题。

感谢感谢！

**Comment by wangzmgit** [comment]
我在播放器中增加了一个Props，可以实现重新加载弹幕列表功能，具体可以看一下文档。

**Comment by Rookie-JiaChen** [comment]
> 我在播放器中增加了一个Props，可以实现重新加载弹幕列表功能，具体可以看一下文档。

感谢，但我这里貌似实现不了重新加载弹幕列表。这是我在页面加载时就调用后端接口获取弹幕信息然后将danmu-key的值+1以便实现刷新弹幕列表，但不知道是哪里出了问题。

```
                       //以下getDanmus方法中的部分内容
                        options.danmaku.data=newDanmuInfo;
                        console.log('后端拉取弹幕数组',options.danmaku.data);
                        freshDanmu++;//更改danmu-key来动态刷新
                        console.log("freshDanmu:",freshDanmu);


onMounted(()=>{
//加载页面就获取弹幕
getDanmus();
}）；


```
后端拉去到三条数据，但播放器显示0条
![Snipaste_2023-02-11_17-59-47](https://user-images.githubusercontent.com/17950010/218252060-b2447603-8513-4d0a-b127-e1974925fbad.png)

![Snipaste_2023-02-11_17-54-27](https://user-images.githubusercontent.com/17950010/218251942-76b2b418-5498-4339-8545-7e8baf4ab9be.png)

**Comment by wangzmgit** [comment]
如果版本没问题的话，把danmaku-key的数据改为响应式数据应该就可以了。

**Comment by Rookie-JiaChen** [comment]
> 如果版本没问题的话，把danmaku-key的数据改为响应式数据应该就可以了。

原来是版本没更新到，已经解决了.非常感谢！
