### ISSUE TITLE
第0秒插入的弹幕没能正确播放，还有播放时间戳支持浮点数么？

### ISSUE THREAD

**Issue by zrorolocete** [wangzmgit/vue-wplayer#4]
![123](https://github.com/user-attachments/assets/3651e151-0f1e-4504-985d-cbcb8d7943ed)
![1234](https://github.com/user-attachments/assets/fc3f194a-d797-4ba7-a36b-6b82d080a561)

可以看到，第一条弹幕0秒插入但是没能播放，第二条1秒插入就可以播放；
同时请问一下插入时间戳粒度为秒是不是粒度有点粗，可以支持毫秒么？

**Comment by wangzmgit** [comment]
> 
> ![123](https://github.com/user-attachments/assets/3651e151-0f1e-4504-985d-cbcb8d7943ed)
> ![1234](https://github.com/user-attachments/assets/fc3f194a-d797-4ba7-a36b-6b82d080a561)
> 
> 可以看到，第一条弹幕0秒插入但是没能播放，第二条1秒插入就可以播放；
> 同时请问一下插入时间戳粒度为秒是不是粒度有点粗，可以支持毫秒么？
> 

换wplayer-next试试，支持毫秒了

**Comment by zrorolocete** [comment]
vue的使用方式基本一致是么

**Comment by zrorolocete** [comment]
读了一下wplayer-next文档https://wplayer-next.interastral-peace.com/
没太看懂，方便给个vue3的demo看看么

**Comment by wangzmgit** [comment]
> 读了一下wplayer-next文档https://wplayer-next.interastral-peace.com/ 没太看懂，方便给个vue3的demo看看么


参考这个https://github.com/wangzmgit/alnitak/blob/master/web/web-client/src/components/video-player/index.vue
或者参考DPlayer相关的文章，这个是基于DPlayer开发的，很多地方都是一样的
